class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome_title': 'Welcome to JobCare',
      'welcome_worker': 'Welcome, Worker',
      'find_job_today': 'Find your dream job today',
      'hero_title': 'Speak to find a Job',
      'hero_subtitle': 'Tap mic and say "Driver job"',
      'job_categories': 'Job Categories',
      'jobs_for_you': 'Jobs for You',
      'see_all': 'See All',
      'applied': 'Applied',
      'saved': 'Saved',
      'interviews': 'Interviews',
      'my_profile': 'My Profile',
      'messages': 'Messages',
      'bol_kar_apply': 'Speak to Apply',
      'voice_assistant': 'VOICE ASSISTANT',
      'processing': 'Processing...',
      'listening': 'Listening...',
      'call_hr': 'Call HR Now',
      'applied_success': 'Applied! HR has received your answers.',
      'speak_to_answer': 'Press & Speak Answer',
      'login': 'Login',
      'signup': 'Sign Up',
      'phone_number': 'Phone Number',
      'get_otp': 'Get OTP',
      'verify_otp': 'Verify OTP',
      'enter_otp': 'Enter the 6-digit code sent to your mobile',
      'resend_otp': 'Resend OTP',
      'otp_description': "We've sent a 6-digit code to",
      'verify': 'Verify',
      'didnt_receive': "Didn't receive the code? ",
      'resend': 'Resend',
      'resend_in': 'Resend code in',
      'full_name': 'Full Name',
      'create_account': 'Create Account',
      'continue': 'Continue',
      'save_profile': 'Save Profile',
      'edit_profile': 'Edit Profile',
      'voice_resume': 'Voice Resume',
      'logout': 'Logout',
      'search_hint': 'Search "Delivery job in Delhi"',
      'no_jobs_found': 'No jobs found',
      'try_voice_search': 'Try searching via voice',
      'job_description': 'Job Description',
      'requirements': 'Requirements',
      'find_jobs': 'Find Jobs',
      'filter_jobs': 'Filter Jobs',
      'salary_range': 'Salary Range',
      'apply_filters': 'Apply Filters',
      'all': 'All',
      'delivery': 'Delivery',
      'driver': 'Driver',
      'construction': 'Construction',
      'security': 'Security',
      'factory': 'Factory',
      'voice_help_title': 'How to use Voice Search',
      'voice_help_desc': 'You can speak naturally to find jobs, update your profile, or navigate the app.',
      'try_saying': 'Try saying:',
      'search_examples': 'Search Examples',
      'nav_examples': 'Navigation Examples',
      'example_search_1': '"Find driver jobs in Bangalore"',
      'example_search_2': '"Show me high paying delivery jobs"',
      'example_search_3': '"Security guard jobs near me"',
      'example_nav_1': '"Open my profile"',
      'example_nav_2': '"Show my applied jobs"',
      'example_nav_3': '"Go to messages"',
      'status_applied': 'Applied',
      'status_under_review': 'Under Review',
      'status_shortlisted': 'Shortlisted',
      'status_interview_scheduled': 'Interview Scheduled',
      'status_selected': 'Selected',
      'status_offered': 'Offered',
      'status_hired': 'Hired',
      'status_rejected': 'Rejected',
      'status_withdrawn': 'Withdrawn',
      'location_not_set': 'Location not set',
      'profile_completion_msg': 'Complete it to get 3x more calls',
      'work_experience': 'Work Experience',
      'education': 'Education',
      'skills': 'Skills',
      'city': 'City',
      'expected_salary': 'Expected Salary (Monthly)',
      'email_address': 'Email Address',
      'new_password': 'New Password',
      'send_otp': 'Send OTP',
      'reset_password': 'Reset Password',
      'change_photo': 'Change Profile Picture',
      'speaking_in': 'SPEAKING IN',
      'profile_complete_title': 'Profile %s%% Complete',
      'voice_resume_pref': 'HRs prefer voice introductions',
      'no_applications': 'No Applications',
      'no_applied_desc': 'You haven\'t applied to any jobs yet.',
      'no_saved_desc': 'Jobs you save will appear here.',
      'no_interviews_desc': 'Upcoming interviews will be shown here.',
      'interview_for': 'Interview for',
      'tomorrow': 'Tomorrow',
      'join_link': 'Join Link',
      'job_type_full_time': 'Full Time',
      'job_type_part_time': 'Part Time',
      'fresher': 'Fresher',
      'experience_years': '%s Years',
    },
    'hi': {
      'welcome_title': 'जॉबकेयर में आपका स्वागत है',
      'welcome_worker': 'नमस्ते, वर्कर',
      'find_job_today': 'आज ही अपनी मनपसंद नौकरी पाएं',
      'hero_title': 'बोल कर नौकरी पाएं',
      'hero_subtitle': 'माइक दबाएं और कहें "ड्राइवर जॉब"',
      'job_categories': 'काम की श्रेणियां',
      'jobs_for_you': 'आपके लिए नौकरियां',
      'see_all': 'सभी देखें',
      'applied': 'आवेदन किया',
      'saved': 'सेव किया',
      'interviews': 'इंटरव्यू',
      'my_profile': 'मेरी प्रोफाइल',
      'messages': 'मैसेज',
      'bol_kar_apply': 'बोल कर अप्लाई करें',
      'voice_assistant': 'वॉयस असिस्टेंट',
      'processing': 'प्रोसेस हो रहा है...',
      'listening': 'सुन रहा हूँ...',
      'call_hr': 'HR को कॉल करें',
      'applied_success': 'सफल! HR को आपके जवाब मिल गए हैं।',
      'speak_to_answer': 'दबाएं और जवाब बोलें',
      'login': 'लॉगिन',
      'signup': 'साइन अप',
      'phone_number': 'फ़ोन नंबर',
      'get_otp': 'OTP प्राप्त करें',
      'verify_otp': 'OTP सत्यापित करें',
      'enter_otp': 'अपने मोबाइल पर भेजा गया 6-अंकों का कोड दर्ज करें',
      'resend_otp': 'OTP पुनः भेजें',
      'otp_description': 'हमने 6-अंकों का कोड भेजा है',
      'verify': 'सत्यापित करें',
      'didnt_receive': 'कोड नहीं मिला? ',
      'resend': 'पुनः भेजें',
      'resend_in': 'कोड पुनः भेजें',
      'full_name': 'पूरा नाम',
      'create_account': 'खाता बनाएं',
      'continue': 'जारी रखें',
      'save_profile': 'प्रोफाइल सेव करें',
      'edit_profile': 'प्रोफाइल बदलें',
      'voice_resume': 'वॉयस रिज्यूमे',
      'logout': 'लॉगआउट',
      'search_hint': 'सर्च करें "दिल्ली में डिलीवरी की जॉब"',
      'no_jobs_found': 'कोई नौकरी नहीं मिली',
      'try_voice_search': 'वॉयस सर्च का उपयोग करें',
      'job_description': 'काम की जानकारी',
      'requirements': 'ज़रूरी शर्तें',
      'find_jobs': 'नौकरी ढूंढें',
      'filter_jobs': 'फिल्टर करें',
      'salary_range': 'सैलरी रेंज',
      'apply_filters': 'फिल्टर लागू करें',
      'all': 'सभी',
      'delivery': 'डिलीवरी',
      'driver': 'ड्राइवर',
      'construction': 'निर्माण',
      'security': 'सुरक्षा',
      'factory': 'फैक्ट्री',
      'voice_help_title': 'वॉयस सर्च का उपयोग कैसे करें',
      'voice_help_desc': 'आप नौकरी खोजने, अपनी प्रोफाइल अपडेट करने या ऐप चलाने के लिए आसानी से बोल सकते हैं।',
      'try_saying': 'ऐसे बोलें:',
      'search_examples': 'सर्च के उदाहरण',
      'nav_examples': 'नेविगेशन के उदाहरण',
      'example_search_1': '"बैंगलोर में ड्राइवर की नौकरी ढूंढें"',
      'example_search_2': '"मुझे ज्यादा सैलरी वाली डिलीवरी जॉब्स दिखाएं"',
      'example_search_3': '"मेरे पास सुरक्षा गार्ड की नौकरियां"',
      'example_nav_1': '"मेरी प्रोफाइल खोलें"',
      'example_nav_2': '"मेरी लागू की गई नौकरियां दिखाएं"',
      'example_nav_3': '"मैसेज पर जाएं"',
      'status_applied': 'आवेदन किया',
      'status_under_review': 'समीक्षा के अधीन',
      'status_shortlisted': 'शॉर्टलिस्ट किया गया',
      'status_interview_scheduled': 'इंटरव्यू तय',
      'status_selected': 'चयनित',
      'status_offered': 'ऑफर दिया गया',
      'status_hired': 'नौकरी मिली',
      'status_rejected': 'अस्वीकृत',
      'status_withdrawn': 'वापस लिया',
      'location_not_set': 'स्थान सेट नहीं है',
      'profile_completion_msg': '3 गुना अधिक कॉल पाने के लिए इसे पूरा करें',
      'work_experience': 'कार्य अनुभव',
      'education': 'शिक्षा',
      'skills': 'कौशल',
      'city': 'शहर',
      'expected_salary': 'अपेक्षित वेतन (मासिक)',
      'email_address': 'ईमेल पता',
      'new_password': 'नया पासवर्ड',
      'send_otp': 'OTP भेजें',
      'reset_password': 'पासवर्ड बदलें',
      'change_photo': 'फोटो बदलें',
      'speaking_in': 'बोलने की भाषा',
      'profile_complete_title': 'प्रोफाइल %s%% पूर्ण',
      'voice_resume_pref': 'एचआर वॉयस परिचय पसंद करते हैं',
      'no_applications': 'कोई आवेदन नहीं',
      'no_applied_desc': 'आपने अभी तक किसी नौकरी के लिए आवेदन नहीं किया है।',
      'no_saved_desc': 'आपके द्वारा सेव की गई नौकरियां यहां दिखाई देंगी।',
      'no_interviews_desc': 'आने वाले इंटरव्यू यहां दिखाए जाएंगे।',
      'interview_for': 'इंटरव्यू',
      'tomorrow': 'कल',
      'join_link': 'लिंक जॉइन करें',
      'job_type_full_time': 'फुल टाइम',
      'job_type_part_time': 'पार्ट टाइम',
      'fresher': 'फ्रेशर',
      'experience_years': '%s साल का अनुभव',
    },
    'kn': {
      'welcome_title': 'ಜಾಬ್‌ಕೇರ್‌ಗೆ ಸ್ವಾಗತ',
      'welcome_worker': 'ನಮಸ್ಕಾರ, ಉದ್ಯೋಗಿ',
      'find_job_today': 'ನಿಮ್ಮ ಕನಸಿನ ಕೆಲಸವನ್ನು ಇಂದು ಹುಡುಕಿ',
      'hero_title': 'ಮಾತನಾಡಿ ಕೆಲಸ ಪಡೆಯಿರಿ',
      'hero_subtitle': 'ಮೈಕ್ ಒತ್ತಿ "ಡ್ರೈವರ್ ಕೆಲಸ" ಎಂದು ಹೇಳಿ',
      'job_categories': 'ಕೆಲಸದ ವರ್ಗಗಳು',
      'jobs_for_you': 'ನಿಮಗಾಗಿ ಕೆಲಸಗಳು',
      'see_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'applied': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
      'saved': 'ಉಳಿಸಲಾಗಿದೆ',
      'interviews': 'ಸಂದರ್ಶನಗಳು',
      'my_profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'messages': 'ಸಂದೇಶಗಳು',
      'bol_kar_apply': 'ಮಾತನಾಡಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'voice_assistant': 'ವಾಯ್ಸ್ ಅಸಿಸ್ಟೆಂಟ್',
      'processing': 'ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...',
      'listening': 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ...',
      'call_hr': 'HR ಗೆ ಕರೆ ಮಾಡಿ',
      'applied_success': 'ಅರ್ಜಿ ಸಲ್ಲಿಕೆ ಯಶಸ್ವಿ! HR ಗೆ ನಿಮ್ಮ ಉತ್ತರಗಳು ತಲುಪಿವೆ.',
      'speak_to_answer': 'ಒತ್ತಿ ಉತ್ತರ ಹೇಳಿ',
      'login': 'ಲಾಗಿನ್',
      'signup': 'ಸೈನ್ ಅಪ್',
      'phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
      'get_otp': 'OTP ಪಡೆಯಿರಿ',
      'verify_otp': 'OTP ಪರಿಶೀಲಿಸಿ',
      'enter_otp': 'ನಿಮ್ಮ ಮೊಬೈಲ್‌ಗೆ ಕಳುಹಿಸಲಾದ 6-ಅಂಕಿಯ ಕೋಡ್ ಅನ್ನು ನಮೂದಿಸಿ',
      'resend_otp': 'OTP ಮತ್ತೆ ಕಳುಹಿಸಿ',
      'otp_description': 'ನಾವು 6-ಅಂಕಿಯ ಕೋಡ್ ಅನ್ನು ಕಳುಹಿಸಿದ್ದೇವೆ',
      'verify': 'ಪರಿಶೀಲಿಸಿ',
      'didnt_receive': 'ಕೋಡ್ ಬಂದಿಲ್ಲವೇ? ',
      'resend': 'ಮತ್ತೆ ಕಳುಹಿಸಿ',
      'resend_in': 'ಕೋಡ್ ಕಳುಹಿಸಲು ಬಾಕಿ ಸಮಯ',
      'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
      'create_account': 'ಖಾತೆ ತೆರೆಯಿರಿ',
      'continue': 'ಮುಂದುವರಿಸಿ',
      'save_profile': 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ',
      'voice_resume': 'ವಾಯ್ಸ್ ರೆಸ್ಯೂಮೆ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'search_hint': 'ಹುಡುಕಿ "ಬೆಂಗಳೂರಿನಲ್ಲಿ ಡೆಲಿವರಿ ಕೆಲಸ"',
      'no_jobs_found': 'ಯಾವುದೇ ಕೆಲಸಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'try_voice_search': 'ವಾಯ್ಸ್ ಮೂಲಕ ಹುಡುಕಿ',
      'job_description': 'ಕೆಲಸದ ವಿವರ',
      'requirements': 'ಅಗತ್ಯತೆಗಳು',
      'find_jobs': 'ಕೆಲಸ ಹುಡುಕಿ',
      'filter_jobs': 'ಫಿಲ್ಟರ್ ಮಾಡಿ',
      'salary_range': 'ಸಂಬಳದ ಶ್ರೇಣಿ',
      'apply_filters': 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ',
      'all': 'ಎಲ್ಲಾ',
      'delivery': 'ಡೆಲಿವರಿ',
      'driver': 'ಚಾಲಕ',
      'construction': 'ನಿರ್ಮಾಣ',
      'security': 'ಭದ್ರತೆ',
      'factory': 'ಕಾರ್ಖಾನೆ',
      'voice_help_title': 'ವಾಯ್ಸ್ ಸರ್ಚ್ ಬಳಸುವುದು ಹೇಗೆ',
      'voice_help_desc': 'ಕೆಲಸ ಹುಡುಕಲು, ಪ್ರೊಫೈಲ್ ಅಪ್‌ಡೇಟ್ ಮಾಡಲು ಅಥವಾ ಆಪ್ ಬಳಸಲು ನೀವು ಸಹಜವಾಗಿ ಮಾತನಾಡಬಹುದು.',
      'try_saying': 'ಹೀಗೆ ಹೇಳಿ:',
      'search_examples': 'ಹುಡುಕಾಟದ ಉದಾಹರಣೆಗಳು',
      'nav_examples': 'ನ್ಯಾವಿಗೇಷನ್ ಉದಾಹರಣೆಗಳು',
      'example_search_1': '"ಬೆಂಗಳೂರಿನಲ್ಲಿ ಚಾಲಕ ಕೆಲಸಗಳನ್ನು ಹುಡುಕಿ"',
      'example_search_2': '"ಹೆಚ್ಚು ಸಂಬಳ ನೀಡುವ ಡೆಲಿವರಿ ಕೆಲಸಗಳನ್ನು ತೋರಿಸಿ"',
      'example_search_3': '"ನನ್ನ ಹತ್ತಿರದ ಸೆಕ್ಯುರಿಟಿ ಗಾರ್ಡ್ ಕೆಲಸಗಳು"',
      'example_nav_1': '"ನನ್ನ ಪ್ರೊಫೈಲ್ ತೆರೆಯಿರಿ"',
      'example_nav_2': '"ನಾನು ಅರ್ಜಿ ಸಲ್ಲಿಸಿದ ಕೆಲಸಗಳನ್ನು ತೋರಿಸಿ"',
      'example_nav_3': '"ಸಂದೇಶಗಳಿಗೆ ಹೋಗಿ"',
      'status_applied': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
      'status_under_review': 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
      'status_shortlisted': 'ಶಾರ್ಟ್‌ಲಿಸ್ಟ್ ಮಾಡಲಾಗಿದೆ',
      'status_interview_scheduled': 'ಸಂದರ್ಶನ ನಿಗದಿಯಾಗಿದೆ',
      'status_selected': 'ಆಯ್ಕೆಯಾಗಿದ್ದಾರೆ',
      'status_offered': 'ಆಫರ್ ನೀಡಲಾಗಿದೆ',
      'status_hired': 'ನೇಮಕಗೊಂಡಿದ್ದಾರೆ',
      'status_rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
      'status_withdrawn': 'ಹಿಂತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ',
      'location_not_set': 'ಸ್ಥಳ ನಿಗದಿಪಡಿಸಿಲ್ಲ',
      'profile_completion_msg': 'ಹೆಚ್ಚಿನ ಕರೆಗಳನ್ನು ಪಡೆಯಲು ಪೂರ್ಣಗೊಳಿಸಿ',
      'work_experience': 'ಕೆಲಸದ ಅನುಭವ',
      'education': 'ಶಿಕ್ಷಣ',
      'skills': 'ಕೌಶಲ್ಯಗಳು',
      'city': 'ನಗರ',
      'expected_salary': 'ನಿರೀಕ್ಷಿತ ಸಂಬಳ (ಮಾಸಿಕ)',
      'email_address': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'new_password': 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'reset_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ',
      'change_photo': 'ಫೋಟೋ ಬದಲಾಯಿಸಿ',
      'speaking_in': 'ಮಾತನಾಡುವ ಭಾಷೆ',
      'profile_complete_title': 'ಪ್ರೊಫೈಲ್ %s%% ಪೂರ್ಣಗೊಂಡಿದೆ',
      'voice_resume_pref': 'ಎಚ್‌ಆರ್ ಧ್ವನಿ ಪರಿಚಯವನ್ನು ಬಯಸುತ್ತಾರೆ',
      'no_applications': 'ಯಾವುದೇ ಅರ್ಜಿಗಳಿಲ್ಲ',
      'no_applied_desc': 'ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಕೆಲಸಕ್ಕೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿಲ್ಲ.',
      'no_saved_desc': 'ನೀವು ಉಳಿಸುವ ಕೆಲಸಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.',
      'no_interviews_desc': 'ಮುಂಬರುವ ಸಂದರ್ಶನಗಳನ್ನು ಇಲ್ಲಿ ತೋರಿಸಲಾಗುತ್ತದೆ.',
      'interview_for': 'ಸಂದರ್ಶನ',
      'tomorrow': 'ನಾಳೆ',
      'join_link': 'ಲಿಂಕ್ ಸೇರಿ',
      'job_type_full_time': 'ಪೂರ್ಣ ಸಮಯ',
      'job_type_part_time': 'ಅರೆಕಾಲಿಕ',
      'fresher': 'ಹೊಸಬರು',
      'experience_years': '%s ವರ್ಷದ ಅನುಭವ',
    },
  };

  static String get(String key, String lang, [List<String>? args]) {
    String value = _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? '';
    if (args != null && args.isNotEmpty) {
      for (var arg in args) {
        value = value.replaceFirst('%s', arg);
      }
    }
    return value;
  }
}
