import api from './api';

const adminService = {
  login: (credentials) => api.post('/admin/login', credentials),
  verifyOtp: (data) => api.post('/admin/verify-otp', data),
  logout: () => api.post('/admin/logout'),
  getProfile: () => api.get('/admin/profile'),

  getDashboard: (params) => api.get('/admin/dashboard', { params }),
  getDashboardStats: () => api.get('/admin/dashboard/stats'),
  getUserGrowth: (params) => api.get('/admin/dashboard/user-growth', { params }),
  getJobTrends: (params) => api.get('/admin/dashboard/job-trends', { params }),
  getApplicationFunnel: () => api.get('/admin/dashboard/application-funnel'),
  getRevenueData: (params) => api.get('/admin/dashboard/revenue', { params }),
  getRecentRegistrations: (params) => api.get('/admin/dashboard/recent-registrations', { params }),
  getSystemHealth: () => api.get('/admin/system/health'),

  getUsers: (params) => api.get('/admin/users', { params }),
  getUserById: (id) => api.get(`/admin/users/${id}`),
  updateUser: (id, data) => api.put(`/admin/users/${id}`, data),
  bulkUpdateUsers: (data) => api.post('/admin/users/bulk-update', data),
  deleteUser: (id) => api.delete(`/admin/users/${id}`),
  bulkDeleteUsers: (ids) => api.post('/admin/users/bulk-delete', { ids }),
  exportUsers: (params) => api.get('/admin/users/export', { params, responseType: 'blob' }),

  getEmployers: (params) => api.get('/admin/employers', { params }),
  getEmployerById: (id) => api.get(`/admin/employers/${id}`),
  verifyEmployer: (id, data) => api.post(`/admin/employers/${id}/verify`, data),
  rejectEmployer: (id, data) => api.post(`/admin/employers/${id}/reject`, data),
  bulkVerifyEmployers: (ids) => api.post('/admin/employers/bulk-verify', { ids }),
  bulkRejectEmployers: (data) => api.post('/admin/employers/bulk-reject', data),
  getEmployerJobs: (id, params) => api.get(`/admin/employers/${id}/jobs`, { params }),

  getJobs: (params) => api.get('/admin/jobs', { params }),
  getJobById: (id) => api.get(`/admin/jobs/${id}`),
  updateJobStatus: (id, data) => api.put(`/admin/jobs/${id}/status`, data),
  flagJob: (id, data) => api.post(`/admin/jobs/${id}/flag`, data),
  unflagJob: (id) => api.post(`/admin/jobs/${id}/unflag`),
  bulkApproveJobs: (ids) => api.post('/admin/jobs/bulk-approve', { ids }),
  bulkRejectJobs: (data) => api.post('/admin/jobs/bulk-reject', data),
  bulkFeatureJobs: (ids) => api.post('/admin/jobs/bulk-feature', { ids }),
  bulkRemoveJobs: (ids) => api.post('/admin/jobs/bulk-remove', { ids }),
  getJobFlags: (id) => api.get(`/admin/jobs/${id}/flags`),

  getApplications: (params) => api.get('/admin/applications', { params }),
  getApplicationById: (id) => api.get(`/admin/applications/${id}`),
  updateApplicationStatus: (id, data) => api.put(`/admin/applications/${id}/status`, data),
  getDuplicateApplications: (params) => api.get('/admin/applications/duplicates', { params }),
  getSpamApplications: (params) => api.get('/admin/applications/spam', { params }),
  markSpam: (id) => api.post(`/admin/applications/${id}/mark-spam`),
  markNotSpam: (id) => api.post(`/admin/applications/${id}/mark-not-spam`),

  getCategories: (params) => api.get('/admin/categories', { params }),
  createCategory: (data) => api.post('/admin/categories', data),
  updateCategory: (id, data) => api.put(`/admin/categories/${id}`, data),
  deleteCategory: (id) => api.delete(`/admin/categories/${id}`),
  reorderCategories: (data) => api.put('/admin/categories/reorder', data),
  getCategorySkills: (id) => api.get(`/admin/categories/${id}/skills`),
  updateCategorySkills: (id, data) => api.put(`/admin/categories/${id}/skills`, data),
  uploadCategoryIcon: (id, formData) => api.post(`/admin/categories/${id}/icon`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),

  getPayments: (params) => api.get('/admin/payments', { params }),
  getPaymentById: (id) => api.get(`/admin/payments/${id}`),
  getRevenueSummary: (params) => api.get('/admin/payments/revenue-summary', { params }),
  getRevenueChart: (params) => api.get('/admin/payments/revenue-chart', { params }),
  getSubscriptions: (params) => api.get('/admin/payments/subscriptions', { params }),
  updateSubscription: (id, data) => api.put(`/admin/payments/subscriptions/${id}`, data),
  cancelSubscription: (id) => api.post(`/admin/payments/subscriptions/${id}/cancel`),
  processRefund: (id, data) => api.post(`/admin/payments/${id}/refund`, data),
  getPayouts: (params) => api.get('/admin/payments/payouts', { params }),
  processPayout: (id, data) => api.post(`/admin/payments/payouts/${id}/process`, data),

  getTickets: (params) => api.get('/admin/support/tickets', { params }),
  getTicketById: (id) => api.get(`/admin/support/tickets/${id}`),
  createTicket: (data) => api.post('/admin/support/tickets', data),
  updateTicket: (id, data) => api.put(`/admin/support/tickets/${id}`, data),
  assignTicket: (id, adminId) => api.post(`/admin/support/tickets/${id}/assign`, { adminId }),
  addTicketReply: (id, data) => api.post(`/admin/support/tickets/${id}/reply`, data),
  resolveTicket: (id) => api.post(`/admin/support/tickets/${id}/resolve`),
  closeTicket: (id) => api.post(`/admin/support/tickets/${id}/close`),
  getKnowledgeBase: (params) => api.get('/admin/support/knowledge-base', { params }),
  createKnowledgeArticle: (data) => api.post('/admin/support/knowledge-base', data),
  updateKnowledgeArticle: (id, data) => api.put(`/admin/support/knowledge-base/${id}`, data),
  deleteKnowledgeArticle: (id) => api.delete(`/admin/support/knowledge-base/${id}`),

  getBanners: (params) => api.get('/admin/cms/banners', { params }),
  createBanner: (data) => api.post('/admin/cms/banners', data),
  updateBanner: (id, data) => api.put(`/admin/cms/banners/${id}`, data),
  deleteBanner: (id) => api.delete(`/admin/cms/banners/${id}`),
  getAnnouncements: (params) => api.get('/admin/cms/announcements', { params }),
  createAnnouncement: (data) => api.post('/admin/cms/announcements', data),
  updateAnnouncement: (id, data) => api.put(`/admin/cms/announcements/${id}`, data),
  deleteAnnouncement: (id) => api.delete(`/admin/cms/announcements/${id}`),
  broadcastNotification: (data) => api.post('/admin/cms/broadcast', data),
  getFeaturedCompanies: (params) => api.get('/admin/cms/featured-companies', { params }),
  addFeaturedCompany: (id) => api.post(`/admin/cms/featured-companies/${id}`),
  removeFeaturedCompany: (id) => api.delete(`/admin/cms/featured-companies/${id}`),
  getFeaturedJobs: (params) => api.get('/admin/cms/featured-jobs', { params }),
  addFeaturedJob: (id) => api.post(`/admin/cms/featured-jobs/${id}`),
  removeFeaturedJob: (id) => api.delete(`/admin/cms/featured-jobs/${id}`),
  getContentSections: () => api.get('/admin/cms/content-sections'),
  updateContentSection: (key, data) => api.put(`/admin/cms/content-sections/${key}`, data),

  getAnalytics: (params) => api.get('/admin/analytics', { params }),
  getUserAcquisition: (params) => api.get('/admin/analytics/user-acquisition', { params }),
  getJobAnalytics: (params) => api.get('/admin/analytics/jobs', { params }),
  getApplicationAnalytics: (params) => api.get('/admin/analytics/applications', { params }),
  getCategoryAnalytics: () => api.get('/admin/analytics/categories'),
  getLocationAnalytics: () => api.get('/admin/analytics/locations'),
  getSalaryAnalytics: () => api.get('/admin/analytics/salaries'),
  getEmployerAnalytics: (params) => api.get('/admin/analytics/employers', { params }),
  exportReport: (params) => api.get('/admin/analytics/export', { params, responseType: 'blob' }),

  getSettings: () => api.get('/admin/settings'),
  updateSettings: (data) => api.put('/admin/settings', data),
  getFeatureToggles: () => api.get('/admin/settings/feature-toggles'),
  updateFeatureToggle: (key, data) => api.put(`/admin/settings/feature-toggles/${key}`, data),
  getEmailTemplates: () => api.get('/admin/settings/email-templates'),
  updateEmailTemplate: (key, data) => api.put(`/admin/settings/email-templates/${key}`, data),
  getApiKeys: () => api.get('/admin/settings/api-keys'),
  createApiKey: (data) => api.post('/admin/settings/api-keys', data),
  revokeApiKey: (id) => api.post(`/admin/settings/api-keys/${id}/revoke`),
  getSecuritySettings: () => api.get('/admin/settings/security'),
  updateSecuritySettings: (data) => api.put('/admin/settings/security', data),
  getSystemLogs: (params) => api.get('/admin/settings/system-logs', { params }),
  getAdmins: () => api.get('/admin/settings/admins'),
  createAdmin: (data) => api.post('/admin/settings/admins', data),
  removeAdmin: (id) => api.delete(`/admin/settings/admins/${id}`),
  toggleMaintenanceMode: (data) => api.post('/admin/settings/maintenance-mode', data),
};

export default adminService;
