# Generated by Django 5.0.14 on 2026-07-22 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('designation', models.CharField(blank=True, default='', max_length=255, verbose_name='designation')),
                ('phone_secondary', models.CharField(blank=True, default='', max_length=20, verbose_name='secondary phone')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_company_admin', models.BooleanField(default=False, verbose_name='company admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employer profile',
                'verbose_name_plural': 'employer profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_verified'], name='employers_e_is_veri_038d42_idx')],
            },
        ),
    ]
