# Generated by Django 5.0.14 on 2026-07-22 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('speech_to_text', 'Speech to Text'), ('text_to_speech', 'Text to Speech'), ('voice_search', 'Voice Search'), ('voice_navigation', 'Voice Navigation')], default='voice_search', max_length=20, verbose_name='session type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('audio_input', models.FileField(blank=True, null=True, upload_to='voice/input/', verbose_name='audio input')),
                ('audio_url', models.URLField(blank=True, default='', max_length=500, verbose_name='audio URL')),
                ('input_text', models.TextField(blank=True, default='', verbose_name='input text')),
                ('output_text', models.TextField(blank=True, default='', verbose_name='output text')),
                ('output_audio_url', models.URLField(blank=True, default='', max_length=500, verbose_name='output audio URL')),
                ('detected_language', models.CharField(blank=True, default='', max_length=20, verbose_name='detected language')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='confidence score')),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='processing time ms')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voice session',
                'verbose_name_plural': 'voice sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'session_type'], name='voice_ai_vo_user_id_aba914_idx'), models.Index(fields=['status'], name='voice_ai_vo_status_3bfa7f_idx')],
            },
        ),
    ]
