# Generated by Django 5.0.14 on 2026-07-22 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=20, verbose_name='status')),
                ('cover_letter', models.TextField(blank=True, default='', verbose_name='cover letter')),
                ('resume_url', models.URLField(blank=True, default='', max_length=500, verbose_name='resume URL')),
                ('voice_resume_url', models.URLField(blank=True, default='', max_length=500, verbose_name='voice resume URL')),
                ('ai_match_score', models.FloatField(blank=True, null=True, verbose_name='AI match score')),
                ('employer_notes', models.TextField(blank=True, default='', verbose_name='employer notes')),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='rejection reason')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='interview date')),
                ('interview_time', models.TimeField(blank=True, null=True, verbose_name='interview time')),
                ('interview_location', models.CharField(blank=True, default='', max_length=500, verbose_name='interview location')),
                ('interview_type', models.CharField(blank=True, choices=[('in_person', 'In Person'), ('video', 'Video'), ('call', 'Call')], max_length=20, null=True, verbose_name='interview type')),
                ('offer_letter_url', models.URLField(blank=True, default='', max_length=500, verbose_name='offer letter URL')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='joined date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='application_job_id_7836e3_idx'), models.Index(fields=['employee', 'status'], name='application_employe_038098_idx'), models.Index(fields=['ai_match_score'], name='application_ai_matc_65e5c3_idx')],
                'unique_together': {('job', 'employee')},
            },
        ),
    ]
