# Generated by Django 5.0.14 on 2026-07-22 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('plan_type', models.CharField(choices=[('job_post', 'Job Post'), ('featured_job', 'Featured Job'), ('employer_subscription', 'Employer Subscription'), ('resume_access', 'Resume Access')], default='employer_subscription', max_length=25, verbose_name='plan type')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=10, verbose_name='billing cycle')),
                ('credits', models.PositiveIntegerField(default=0, help_text='Number of job posts or resume views', verbose_name='credits')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='features')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='status')),
                ('credits_remaining', models.PositiveIntegerField(default=0, verbose_name='credits remaining')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='auto renew')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.subscriptionplan')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_for', models.CharField(choices=[('subscription', 'Subscription'), ('job_post', 'Job Post'), ('featured_job', 'Featured Job'), ('resume_access', 'Resume Access')], default='subscription', max_length=20, verbose_name='payment for')),
                ('razorpay_order_id', models.CharField(max_length=255, unique=True, verbose_name='Razorpay order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Razorpay payment ID')),
                ('razorpay_signature', models.TextField(blank=True, default='', verbose_name='Razorpay signature')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10, verbose_name='status')),
                ('payment_data', models.JSONField(blank=True, default=dict, verbose_name='payment data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.subscription')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'), models.Index(fields=['razorpay_order_id'], name='payments_pa_razorpa_86ad18_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='payments_su_user_id_058311_idx'),
        ),
    ]
