# Generated by Django 5.0.14 on 2026-07-22 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='icon')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('state', models.CharField(db_index=True, max_length=255, verbose_name='state')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='jobs.category')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('responsibilities', models.JSONField(blank=True, default=list, verbose_name='responsibilities')),
                ('requirements', models.JSONField(blank=True, default=list, verbose_name='requirements')),
                ('skills_required', models.JSONField(blank=True, default=list, verbose_name='skills required')),
                ('experience_min', models.PositiveIntegerField(default=0, verbose_name='min experience')),
                ('experience_max', models.PositiveIntegerField(default=0, verbose_name='max experience')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='min salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='max salary')),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('hourly', 'Hourly')], default='monthly', max_length=10, verbose_name='salary type')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='location')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='state')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], db_index=True, default='full_time', max_length=20, verbose_name='job type')),
                ('shift_timing', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('flexible', 'Flexible')], default='day', max_length=10, verbose_name='shift timing')),
                ('education_required', models.JSONField(blank=True, default=list, verbose_name='education required')),
                ('benefits', models.JSONField(blank=True, default=list, verbose_name='benefits')),
                ('openings', models.PositiveIntegerField(default=1, verbose_name='openings')),
                ('urgency', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='urgency')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('filled', 'Filled')], db_index=True, default='active', max_length=10, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='urgent')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('application_count', models.PositiveIntegerField(default=0, verbose_name='application count')),
                ('save_count', models.PositiveIntegerField(default=0, verbose_name='save count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['status', 'job_type', 'city'], name='jobs_job_status_1201b8_idx'), models.Index(fields=['company', 'status'], name='jobs_job_company_797da4_idx'), models.Index(fields=['category', 'status'], name='jobs_job_categor_2e2729_idx'), models.Index(fields=['experience_min', 'experience_max'], name='jobs_job_experie_91ef99_idx'), models.Index(fields=['salary_min', 'salary_max'], name='jobs_job_salary__2892b4_idx'), models.Index(fields=['latitude', 'longitude'], name='jobs_job_latitud_d115f8_idx')],
            },
        ),
    ]
