# Generated by Django 5.0.14 on 2026-07-22 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='company name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='logo')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='company/banners/', verbose_name='banner image')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='images')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('website', models.URLField(blank=True, default='', max_length=500, verbose_name='website')),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('construction', 'Construction'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('media', 'Media'), ('agriculture', 'Agriculture'), ('energy', 'Energy'), ('other', 'Other')], max_length=50, null=True, verbose_name='industry')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1000+', '1000+ employees')], max_length=10, null=True, verbose_name='company size')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='founded year')),
                ('headquarters', models.CharField(blank=True, default='', max_length=255, verbose_name='headquarters')),
                ('locations', models.JSONField(blank=True, default=list, verbose_name='locations')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='verification status')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='company/verification/', verbose_name='verification document')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='social links')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=255, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='contact phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'industry'], name='companies_c_name_7f5a45_idx'), models.Index(fields=['verification_status'], name='companies_c_verific_2cd7c4_idx'), models.Index(fields=['is_featured'], name='companies_c_is_feat_113e84_idx')],
            },
        ),
    ]
