global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'django'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'django-api'

  - job_name: 'postgresql'
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgresql'

  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'

  - job_name: 'celery'
    scrape_interval: 15s
    static_configs:
      - targets: ['celery-exporter:9808']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'celery'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'node'

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'cadvisor'
