# Generated by Django 5.0.14 on 2026-07-24 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('kannada', 'Kannada'), ('tamil', 'Tamil'), ('english', 'English')], default='hindi', max_length=20, verbose_name='language')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], default='in_progress', max_length=20, verbose_name='status')),
                ('current_question_index', models.PositiveIntegerField(default=0, verbose_name='current question index')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('provider_call_sid', models.CharField(max_length=100, unique=True, verbose_name='provider call SID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='AI summary')),
                ('profile_data', models.JSONField(blank=True, default=dict, verbose_name='profile data')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='intake_pdfs/', verbose_name='PDF file')),
            ],
            options={
                'verbose_name': 'call session',
                'verbose_name_plural': 'call sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='order')),
                ('question_text_en', models.TextField(verbose_name='question text (EN)')),
                ('question_key', models.SlugField(choices=[('name', 'Name'), ('education', 'Education'), ('location', 'Location'), ('job_interest', 'Job Interest'), ('experience', 'Experience'), ('skills', 'Skills'), ('salary_expectation', 'Expected Salary')], verbose_name='question key')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'intake question',
                'verbose_name_plural': 'intake questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CallAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(verbose_name='answer text')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('audio_recording_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='audio recording URL')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='answered at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='call_intake.callsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='call_intake.intakequestion')),
            ],
            options={
                'verbose_name': 'call answer',
                'verbose_name_plural': 'call answers',
                'ordering': ['answered_at'],
            },
        ),
    ]
