# Generated by Django 5.0.14 on 2026-07-22 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20, null=True, verbose_name='gender')),
                ('address', models.TextField(blank=True, default='', verbose_name='address')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='state')),
                ('pincode', models.CharField(blank=True, default='', max_length=10, verbose_name='pincode')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='skills')),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='experience years')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='education')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='languages')),
                ('certificates', models.JSONField(blank=True, default=list, verbose_name='certificates')),
                ('resume_url', models.URLField(blank=True, default='', max_length=500, verbose_name='resume URL')),
                ('voice_resume_url', models.URLField(blank=True, default='', max_length=500, verbose_name='voice resume URL')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='expected salary')),
                ('preferred_job_categories', models.JSONField(blank=True, default=list, verbose_name='preferred job categories')),
                ('preferred_locations', models.JSONField(blank=True, default=list, verbose_name='preferred locations')),
                ('availability', models.CharField(choices=[('immediate', 'Immediate'), ('notice_period', 'Notice Period'), ('not_available', 'Not Available')], default='not_available', max_length=20, verbose_name='availability')),
                ('aadhaar_number', models.CharField(blank=True, default='', max_length=12, verbose_name='aadhaar number')),
                ('aadhaar_verified', models.BooleanField(default=False, verbose_name='aadhaar verified')),
                ('profile_completion_score', models.FloatField(default=0.0, verbose_name='profile completion score')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='profile complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee profile',
                'verbose_name_plural': 'employee profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'availability'], name='users_emplo_city_d17380_idx'), models.Index(fields=['experience_years'], name='users_emplo_experie_4b1060_idx')],
            },
        ),
    ]
